FROM registry.access.redhat.com/rhel7/rhel

RUN rpm -i https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

RUN curl https://packages.microsoft.com/config/rhel/7/prod.repo | tee /etc/yum.repos.d/microsoft.repo

RUN yum-config-manager --enable rhel-server-rhscl-7-rpms rhel-7-server-extras-rpms rhel-7-server-dotnet-rpms && yum -y install ca-certificates \
        curl \
        libicu \
	java-11-openjdk-devel \
        jq \
	nmap-ncat \
	powershell \
	rh-dotnet31 \
	sudo \
        zip \
        unzip 

#RUN ln -s podman docker
WORKDIR /azp
COPY ./agentgroups .
RUN cat agentgroups >> /etc/sudoers
COPY ./gitcreate.sh .
COPY ./start.sh .
RUN chmod +x gitcreate.sh start.sh
RUN ./gitcreate.sh
RUN useradd agent
ENV PATH="/opt/rh/rh-dotnet31/root/usr/bin:/opt/rh/rh-dotnet31/root/usr/sbin:${PATH}"
ENV DOTNET_ROOT=/opt/rh/rh-dotnet31/root/usr/lib64/dotnet
RUN chown -R agent:agent /azp
USER agent

CMD ["./start.sh"]
